export const  statusIcon = {
	'WeInPlanning':{
		'color':'',
		'icon':'play',
		'nohandle':true,
		'next':'WeApproved',
		'alt':'点击开始',
		'time':'actualStartDate',
	},
	'WeApproved':{
		'color':'',
		'icon':'play',
		'nohandle':false,
		'next':'WeInProgress',
		'alt':'点击开始',
		'time':'actualStartDate',
	},
	'WeInProgress':{
		'color':'#ff8582',
		'icon':'stop',
		'nohandle':false,
		'next':'WeComplete',
		'alt':'点击结束',
		'time':'actualCompletionDate'
	},
	'WeInHold':{
		'color':'#ff8582',
		'icon':'pause',
		'nohandle':false,
		'next':'WeInProgress',
		'alt':'点击开始',
		'time':'actualStartDate'
	},
	'WeComplete':{
		'color':'',
		'icon':'loop',
		'nohandle':false,
		'next':'WeInProgress',
		'alt':'点击重置',
		'time':'actualCompletionDate'
	}
}