let data = {
  "tasks": [

    { "id": 11, "name": "Gantt editor", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1", "level": 0, "status": "STATUS_ACTIVE", "depends": "", "canWrite": true, "start": 1522512000000, "duration": 20, "end": 1523376000000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": true, "parentID":"" },
    { "id": -2, "name": "coding", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.1", "level": 1, "status": "STATUS_ACTIVE", "depends": "", "canWrite": true, "start": 1522598400000, "duration": 10, "end": 1522684800000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": true , "parentID":""},
    { "id": -3, "name": "gantt part", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.1.1", "level": 2, "status": "STATUS_ACTIVE", "depends": "", "canWrite": true, "start": 1522598400000, "duration": 8, "end": 1522857600000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": false, "parentID":"" },
    { "id": -4, "name": "editor part", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.1.2", "level": 2, "status": "STATUS_SUSPENDED", "depends": "", "canWrite": true, "start": 1522684800000, "duration": 5, "end": 1522944000000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": false, "parentID":"" },
    { "id": -5, "name": "testing", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.2", "level": 1, "status": "STATUS_SUSPENDED", "depends": "", "canWrite": true, "start": 1522771200000, "duration": 5, "end": 1523030400000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": true , "parentID":""},
    { "id": -6, "name": "test on safari", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.2.1", "level": 2, "status": "STATUS_SUSPENDED", "depends": "", "canWrite": true, "start": 1522857600000, "duration": 9, "end": 1523116800000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": false, "parentID":"" },
    { "id": -7, "name": "test on ie", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.2.2", "level": 2, "status": "STATUS_SUSPENDED", "depends": "6", "canWrite": true, "start": 1522944000000, "duration": 9, "end": 1523289600000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": false, "parentID":"" },
    { "id": -8, "name": "test on chrome", "progress": 0, "progressByWorklog": false, "relevance": 0, "type": "", "typeId": "", "description": "", "code": "1.2.3", "level": 2, "status": "STATUS_SUSPENDED", "depends": "6", "canWrite": true, "start": 1523030400000, "duration": 9, "end": 1523376000000, "startIsMilestone": false, "endIsMilestone": false, "collapsed": false, "assigs": [], "hasChild": false, "parentID":"" },


  ],   
  "deletedTaskIds": [],   
  "resources": [     
  { "id": "tmp_1", "name":
"Resource 1" },     
{ "id": "tmp_2", "name": "Resource 2" },     
{ "id":
"tmp_3", "name": "Resource 3" },     
{ "id": "tmp_4", "name": "Resource 4" }
],   
"roles": [     { "id": "tmp_1", "name": "Project Manager" },     { "id":
"tmp_2", "name": "Worker" },     { "id": "tmp_3", "name": "Stakeholder" },
{ "id": "tmp_4", "name": "Customer" }   ],   "selectedRow": 2,   "canWrite":
true,   "canDelete": true,   "canWriteOnParent": true,   "canAdd": true }


let data1 = 
{
　　"ok":true,
　　"project":{
　　　　"tasks":[
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"actualWorkTime":80,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"workEffortTypeEnumId":"WetProject",
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"description":"2018春季订货会款式研发项目介绍信息",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"visibilityEnumId":"WevWorkGroup",
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"totalClientCostAllowed":10000,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"statusId":"WeInProgress",
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"estimatedStartDate":"2018-03-10 00:00:00.000",
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"statusFlowId":"Default",
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"actualCost":5550,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":1,
　　　　　　　　"workEffortName":"2018春季订货会款式研发",
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"estimatedCompletionDate":"2018-04-30 00:00:00.000",
　　　　　　　　"totalTimeAllowed":200,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-27 19:18:14.997",
　　　　　　　　"actualClientCost":8880,
　　　　　　　　"location":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"workEffortId":"2018KSDJ",
　　　　　　　　"level":0,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":true
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedStartDate":"2018-03-12 00:00:00.000",
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"workEffortId":"2018KSDJ-M1",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"workEffortName":"市场调研",
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 17:05:55.889",
　　　　　　　　"estimatedCompletionDate":"2018-03-16 00:00:00.000",
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"statusId":"WeApproved",
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:32:18.415",
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"workEffortId":"2018KSDJ-M2",
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"workEffortName":"商品企划",
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"estimatedCompletionDate":"2018-03-22 00:00:00.000",
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"estimatedStartDate":"2018-03-19 00:00:00.000",
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"workEffortName":"款式设计",
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortId":"2018KSDJ-M3",
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:34:58.423",
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"estimatedCompletionDate":"2018-03-30 00:00:00.000",
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"estimatedStartDate":"2018-03-26 00:00:00.000",
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortId":"2018KSDJ-M4",
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:33:29.451",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"estimatedStartDate":"2018-04-02 00:00:00.000",
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"estimatedCompletionDate":"2018-04-06 00:00:00.000",
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"workEffortName":"版型打版",
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"workEffortId":"2018KSDJ-M5",
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:34:13.289",
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"estimatedStartDate":"2018-04-09 00:00:00.000",
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"estimatedCompletionDate":"2018-04-13 00:00:00.000",
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"workEffortName":"工艺算料",
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"workEffortId":"2018KSDJ-M6",
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"estimatedStartDate":"2018-04-16 00:00:00.000",
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"workEffortName":"工艺说明开发",
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:34:48.014",
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"estimatedCompletionDate":"2018-04-20 00:00:00.000",
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"workEffortId":"2018KSDJ-M7",
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"workEffortName":"样衣制作",
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"estimatedCompletionDate":"2018-04-27 00:00:00.000",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:35:51.289",
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"estimatedStartDate":"2018-04-23 00:00:00.000",
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"workEffortTypeEnumId":"WetMilestone",
　　　　　　　　"revisionNumber":null,
　　　　　　　　"workEffortName":"评审确认款式",
　　　　　　　　"allDayEnd":null,
　　　　　　　　"workEffortId":"2018KSDJ-M8",
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"statusId":"WeInPlanning",
　　　　　　　　"estimatedCompletionDate":"2018-05-02 00:00:00.000",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"purposeEnumId":null,
　　　　　　　　"resolutionEnumId":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-14 16:36:41.269",
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"estimatedStartDate":"2018-04-30 00:00:00.000",
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"actualWorkTime":null,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":false
　　　　　　},
　　　　　　{
　　　　　　　　"recurStartCron":null,
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-15 00:42:03.052",
　　　　　　　　"workEffortName":"风格规划",
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"statusId":"WeInProgress",
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"workEffortTypeEnumId":"WetTask",
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"timeUomId":"TF_hr",
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":450,
　　　　　　　　"actualClientCost":720,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"estimatedStartDate":"2018-03-11 00:00:00.000",
　　　　　　　　"parentWorkEffortId":null,
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":1,
　　　　　　　　"workEffortId":"2018KSDJ-100000",
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"purposeEnumId":"WepTask",
　　　　　　　　"allDayStart":null,
　　　　　　　　"estimatedCompletionDate":"2018-03-17 00:00:00.000",
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"location":null,
　　　　　　　　"resolutionEnumId":"WerUnresolved",
　　　　　　　　"actualWorkTime":6,
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"ownerPartyId":"EX_JOHN_DOE",
　　　　　　　　"level":1,
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"milestoneWorkEffortId":"",
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　],
　　　　　　　　"hasChild":true
　　　　　　},
　　　　　　{
　　　　　　　　"level":2,
　　　　　　　　"recurStartCron":null,
　　　　　　　　"revisionNumber":null,
　　　　　　　　"allDayEnd":null,
　　　　　　　　"statusFlowId":null,
　　　　　　　　"description":null,
　　　　　　　　"estimatedSetupTime":null,
　　　　　　　　"shipmentMethodEnumId":null,
　　　　　　　　"actualSetupTime":null,
　　　　　　　　"recurEndDate":null,
　　　　　　　　"infoUrl":null,
　　　　　　　　"universalId":null,
　　　　　　　　"statusId":"WeInProgress",
　　　　　　　　"workEffortName":"买手市场调研",
　　　　　　　　"estimatedWorkTime":null,
　　　　　　　　"workEffortTypeEnumId":"WetTask",
　　　　　　　　"remainingWorkTime":null,
　　　　　　　　"actualStartDate":null,
　　　　　　　　"costUomId":null,
　　　　　　　　"actualCost":null,
　　　　　　　　"estimatedWorkDuration":null,
　　　　　　　　"timeUomId":null,
　　　　　　　　"facilityId":null,
　　　　　　　　"recurLimit":null,
　　　　　　　　"sourceReferenceId":null,
　　　　　　　　"estimatedStartDate":"2018-03-11 00:00:00.000",
　　　　　　　　"sendNotificationEmail":null,
　　　　　　　　"percentComplete":null,
　　　　　　　　"totalTimeAllowed":null,
　　　　　　　　"rootWorkEffortId":"2018KSDJ",
　　　　　　　　"priority":null,
　　　　　　　　"workEffortId":"2018KSDJ-100001",
　　　　　　　　"actualClientCost":null,
　　　　　　　　"actualWorkDuration":null,
　　　　　　　　"workTypeEnumId":null,
　　　　　　　　"totalClientCostAllowed":null,
　　　　　　　　"parentWorkEffortId":"2018KSDJ-100000",
　　　　　　　　"ownerPartyId":null,
　　　　　　　　"purposeEnumId":"WepTask",
　　　　　　　　"actualWorkTime":0,
　　　　　　　　"allDayStart":null,
　　　　　　　　"actualCompletionDate":null,
　　　　　　　　"lastUpdatedStamp":"2018-03-17 19:18:14.997",
　　　　　　　　"location":null,
　　　　　　　　"resolutionEnumId":"WerUnresolved",
　　　　　　　　"visibilityEnumId":null,
　　　　　　　　"actualBreakDuration":null,
　　　　　　　　"estimatedCompletionDate":"2018-03-17 00:00:00.000",
　　　　　　　　"canWrite":true,
　　　　　　　　"collapsed":false,
　　　　　　　　"milestoneWorkEffortId":"",
　　　　　　　　"depends":[

　　　　　　　　],
　　　　　　　　"assigns":[

　　　　　　　　]
　　　　　　},
// 　　　　　　{
// 　　　　　　　　"recurStartCron":null,
// 　　　　　　　　"revisionNumber":null,
// 　　　　　　　　"allDayEnd":null,
// 　　　　　　　　"statusFlowId":null,
// 　　　　　　　　"description":null,
// 　　　　　　　　"estimatedSetupTime":null,
// 　　　　　　　　"shipmentMethodEnumId":null,
// 　　　　　　　　"statusId":"WeInPlanning",
// 　　　　　　　　"purposeEnumId":"WepPlaceholder",
// 　　　　　　　　"actualSetupTime":null,
// 　　　　　　　　"workEffortId":"2018KSDJ-100051",
// 　　　　　　　　"recurEndDate":null,
// 　　　　　　　　"infoUrl":null,
// 　　　　　　　　"universalId":null,
// 　　　　　　　　"estimatedWorkTime":null,
// 　　　　　　　　"workEffortTypeEnumId":"WetTask",
// 　　　　　　　　"workEffortName":"20个新款设计",
// 　　　　　　　　"remainingWorkTime":null,
// 　　　　　　　　"actualStartDate":null,
// 　　　　　　　　"timeUomId":"TF_hr",
// 　　　　　　　　"costUomId":null,
// 　　　　　　　　"actualCost":null,
// 　　　　　　　　"priority":5,
// 　　　　　　　　"estimatedWorkDuration":null,
// 　　　　　　　　"facilityId":null,
// 　　　　　　　　"recurLimit":null,
// 　　　　　　　　"sourceReferenceId":null,
// 　　　　　　　　"estimatedStartDate":null,
// 　　　　　　　　"parentWorkEffortId":null,
// 　　　　　　　　"sendNotificationEmail":null,
// 　　　　　　　　"percentComplete":null,
// 　　　　　　　　"totalTimeAllowed":null,
// 　　　　　　　　"rootWorkEffortId":"2018KSDJ",
// 　　　　　　　　"actualClientCost":null,
// 　　　　　　　　"actualWorkDuration":null,
// 　　　　　　　　"lastUpdatedStamp":"2018-03-15 00:50:02.693",
// 　　　　　　　　"workTypeEnumId":null,
// 　　　　　　　　"totalClientCostAllowed":null,
// 　　　　　　　　"estimatedCompletionDate":"2018-04-30 00:00:00.000",
// 　　　　　　　　"actualWorkTime":0,
// 　　　　　　　　"allDayStart":null,
// 　　　　　　　　"actualCompletionDate":null,
// 　　　　　　　　"location":null,
// 　　　　　　　　"resolutionEnumId":"WerUnresolved",
// 　　　　　　　　"visibilityEnumId":null,
// 　　　　　　　　"actualBreakDuration":null,
// 　　　　　　　　"ownerPartyId":"EX_JOHN_DOE",
// 　　　　　　　　"level":2,
// 　　　　　　　　"canWrite":true,
// 　　　　　　　　"collapsed":false,
// 　　　　　　　　"milestoneWorkEffortId":"",
// 　　　　　　　　"depends":[

// 　　　　　　　　],
// 　　　　　　　　"assigns":[

// 　　　　　　　　]
// 　　　　　　},



　　　　],
　　　　"resources":[
          {
            "partyId": "tmp_1",
            "partyName": "Resource 1"
          }, 
          {
            "partyId": "tmp_2",
            "partyName": "Resource 2"
          }, 
          {
              "partyId": "tmp_3",
              "partyName": "Resource 3"
          }, 
          {
              "partyId": "tmp_4",
              "partyName": "Resource 4"
          }
        ],
　　　　"roles":[
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Assignee",
　　　　　　　　"roleTypeId":"Assignee",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"description":"Business Analyst",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"BusinessAnalyst",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"ClientBilling",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Client Billing Rep",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"ClientManager",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Client Manager",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Customer",
　　　　　　　　"roleTypeId":"Customer",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"CustomerBillTo",
　　　　　　　　"parentTypeId":"Customer",
　　　　　　　　"description":"Customer - Bill To",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"description":"Default Assignee",
　　　　　　　　"roleTypeId":"DefaultAssignee",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"ExpertUser",
　　　　　　　　"description":"Expert User",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"Manager",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Manager",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Programmer",
　　　　　　　　"roleTypeId":"Programmer",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"ProgrammerLead",
　　　　　　　　"description":"Programmer Lead",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"description":"Project Manager",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"ProjectManager",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"description":"Quality Analyst",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"QualityAnalyst",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"QualityLead",
　　　　　　　　"description":"Quality Lead",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"SysAdmin",
　　　　　　　　"description":"System Administrator",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"SysArchitect",
　　　　　　　　"roleGroupEnumId":"RgpProject",
　　　　　　　　"description":"System Architect"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Team",
　　　　　　　　"roleTypeId":"OrgTeam",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"UiDesigner",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"UI Designer",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Vendor",
　　　　　　　　"roleGroupEnumId":"RgpProject",
　　　　　　　　"roleTypeId":"Vendor"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"VendorBillFrom",
　　　　　　　　"parentTypeId":"Vendor",
　　　　　　　　"description":"Vendor - Bill From",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　}
　　　　],
　　　　"canWrite":true,
　　　　"canDelete":true,
　　　　"canWriteOnParent":true,
　　　　"canAdd":true
　　}
}


let data2 = {
　　"tasks":[
　　{
　　　　"id":-1,
　　　　"name":"Gantt editor",
　　　　"code":"",
　　　　"level":0,
　　　　"status":"STATUS_ACTIVE",
　　　　"canWrite":true,
　　　　"start":1396994400000,
　　　　"duration":21,
　　　　"end":1399672799999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"hasChild":true
　　},
　　{
　　　　"id":-2,
　　　　"name":"coding",
　　　　"code":"",
　　　　"level":1,
　　　　"status":"STATUS_ACTIVE",
　　　　"canWrite":true,
　　　　"start":1396994400000,
　　　　"duration":10,
　　　　"end":1398203999999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"description":"",
　　　　"progress":0,
　　　　"hasChild":true
　　},
　　{
　　　　"id":-3,
　　　　"name":"gantt part",
　　　　"code":"",
　　　　"level":2,
　　　　"status":"STATUS_ACTIVE",
　　　　"canWrite":true,
　　　　"start":1396994400000,
　　　　"duration":2,
　　　　"end":1397167199999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"",
　　　　"hasChild":false
　　},
　　{
　　　　"id":-4,
　　　　"name":"editor part",
　　　　"code":"",
　　　　"level":2,
　　　　"status":"STATUS_SUSPENDED",
　　　　"canWrite":true,
　　　　"start":1397167200000,
　　　　"duration":4,
　　　　"end":1397685599999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"3",
　　　　"hasChild":false
　　},
　　{
　　　　"id":-5,
　　　　"name":"testing",
　　　　"code":"",
　　　　"level":1,
　　　　"status":"STATUS_SUSPENDED",
　　　　"canWrite":true,
　　　　"start":1398981600000,
　　　　"duration":6,
　　　　"end":1399672799999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"2:5",
　　　　"description":"",
　　　　"progress":0,
　　　　"hasChild":true
　　},
　　{
　　　　"id":-6,
　　　　"name":"test on safari",
　　　　"code":"",
　　　　"level":2,
　　　　"status":"STATUS_SUSPENDED",
　　　　"canWrite":true,
　　　　"start":1398981600000,
　　　　"duration":2,
　　　　"end":1399327199999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"",
　　　　"hasChild":false
　　},
　　{
　　　　"id":-7,
　　　　"name":"test on ie",
　　　　"code":"",
　　　　"level":2,
　　　　"status":"STATUS_SUSPENDED",
　　　　"canWrite":true,
　　　　"start":1399327200000,
　　　　"duration":3,
　　　　"end":1399586399999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"6",
　　　　"hasChild":false
　　},
　　{
　　　　"id":-8,
　　　　"name":"test on chrome",
　　　　"code":"",
　　　　"level":2,
　　　　"status":"STATUS_SUSPENDED",
　　　　"canWrite":true,
　　　　"start":1399327200000,
　　　　"duration":2,
　　　　"end":1399499999999,
　　　　"startIsMilestone":false,
　　　　"endIsMilestone":false,
　　　　"collapsed":false,
　　　　"assigs":[

　　　　],
　　　　"depends":"6",
　　　　"hasChild":false
　　}
],
　　　　"resources":[
          {
            "partyId": "tmp_1",
            "partyName": "Resource 1"
          }, 
          {
            "partyId": "tmp_2",
            "partyName": "Resource 2"
          }, 
          {
              "partyId": "tmp_3",
              "partyName": "Resource 3"
          }, 
          {
              "partyId": "tmp_4",
              "partyName": "Resource 4"
          }
        ],
　　　　"roles":[
　　　　　　{
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Assignee",
　　　　　　　　"roleTypeId":"Assignee",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"description":"Business Analyst",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"roleTypeId":"BusinessAnalyst",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　},
　　　　　　{
　　　　　　　　"roleTypeId":"ClientBilling",
　　　　　　　　"parentTypeId":null,
　　　　　　　　"description":"Client Billing Rep",
　　　　　　　　"roleGroupEnumId":"RgpProject"
　　　　　　}

　　　　],
　　"selectedRow":0,
　　"canWrite":true,
　　"canWriteOnParent":true,
　　"canDelete":true,
    "canAdd":true
}


export default data1
